services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend-api/.env
    volumes:
      - .:/app
    working_dir: /app/backend-api # Set working directory to backend-api
    command: flask run --host=0.0.0.0 --port=5000
    depends_on:
      - redis
    networks:
      - backend_network

  celery-worker:
    build: .
    env_file:
      - backend-api/.env
    volumes:
      - .:/app
    working_dir: /app/backend-api # Ensure Celery runs inside backend-api
    environment:
      - PYTHONPATH=/app/backend-api # Add backend-api to PYTHONPATH
    command: celery -A celery_app.celery worker --loglevel=info
    depends_on:
      - redis
      - web
    networks:
      - backend_network

  celery-beat:
    build: .
    env_file:
      - backend-api/.env
    volumes:
      - .:/app
    working_dir: /app/backend-api # Ensure Celery runs inside backend-api
    environment:
      - PYTHONPATH=/app/backend-api # Add backend-api to PYTHONPATH
    command: celery -A celery_app.celery beat --loglevel=info
    depends_on:
      - redis
      - web
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
